services:
    webserver:
        build:
            context: docker/webserver
            args:
                - WWW_DATA_UID=${WWW_DATA_UID:-orig}
                - WWW_DATA_GID=${WWW_DATA_GID:-orig}

        expose:
            - 80
        ports:
            - ${APP_PORT:-80}:80
        volumes:
            - .:/var/www/html
        environment:
            APACHE_DOCUMENT_ROOT: /var/www/html/public
    db:
        image: mysql:8.3
        expose:
            - 3306
        volumes:
            - db_data:/var/lib/mysql
            - .:/mnt
        working_dir: /mnt
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: thedatabase
            MYSQL_USER: user
            MYSQL_PASSWORD: userpass
    node:
        build:
            context: docker/node
            args:
                - API_WWW_DATA_UID=${WWW_DATA_UID:-orig}
                - API_WWW_DATA_GID=${WWW_DATA_GID:-orig}
        volumes:
            - .:/workspace
volumes:
    db_data: